version: '3'
services:
  app:
    build: .
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
      - elasticsearch
    networks:
      - search-engine

  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - search-engine

  rabbitmq:
    image: rabbitmq:3.9.5-alpine
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - search-engine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - search-engine

volumes:
  db_data:

networks:
  search-engine:
    driver: bridge