spring:
  application:
    name: crawler-app

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: root

  redis:
    enabled: true
    host: redis
    port: 6379

elasticsearch:
  host: elasticsearch
  port: 9200

server:
  port: 8080

crawler:
  queue:
    name: crawl-task
  index:
    strategy: llm  # Options: elasticsearch, llm
