version: 2
jobs:
  build:
    docker:
      - image: maven
    working_directory: ~/app
    steps:
      - checkout
      - run: mvn clean install
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
